print("First 10 letters in Lowercase : ")
t=head(letters,10)
print(t)
print("Last 10 letters in Uppercase : ")
t=tail(LETTERS,10)
print(t)
print("Letters between 22nd and 24th letters in Uppercase : ")
e=tail(LETTERS[22:24])
print(e)